### ISSUE TITLE
Failed to run the analysis due to `lief` breaking changes: Missing `EXE_FORMATS` and `Binary.name Attributes`

### ISSUE THREAD

**Issue by Cycatz** [unikraft/loupe#14]
First, big thanks for making the loupe available in public! It would definitely benefit people who want to observe the behaviors between the applications and OS.

However, while playing with loupe by following the guide on README, I encountered several errors, mostly are due to Python `lief` library.

One error is that `EXE_FORMATS` attribute doesn't exist:
```
$ ./loupe generate -b -db ../loupedb -a "nginx" -w "wrk" -d ./Dockerfile.nginx
[I] Checking database...
[W] Dockerfile (Dockerfile.nginx) calls explore.py without the --final-check option, which is recommended.
[I] Building container...
Sending build context to Docker daemon  4.096kB
Step 1/13 : FROM loupe-base:latest
 ---> 4342dd3c9e4c
Step 2/13 : RUN apt update
 ---> Running in bd68334ab3f7
...
Step 13/13 : CMD /root/explore.py --output-csv -t /root/nginx-test.sh                -b /root/nginx/objs/nginx               -- -p /root/nginx -g "daemon off;"
 ---> Running in 586f72c51988
Removing intermediate container 586f72c51988
 ---> 30d8a20ace7c
Successfully built 30d8a20ace7c
Successfully tagged nginx-loupe:latest
[I] Running dynamic analysis in the container (2 replicas)...
Traceback (most recent call last):
  File "/root/src/static-binary-analyser/static_analyser.py", line 126, in <module>
    main()
  File "/root/src/static-binary-analyser/static_analyser.py", line 90, in main
    if not is_valid_binary(binary):
  File "/root/src/static-binary-analyser/elf_analyser.py", line 63, in is_valid_binary
    and binary.format == lief.EXE_FORMATS.ELF
AttributeError: module 'lief' has no attribute 'EXE_FORMATS'
...
[I] Sanitizing replicas outputs...
[E] Binary static analysis results are invalid (no results!)
```
After some investigation, I found it was due to the breaking changes of lief (as introduced in [14.0](https://lief-project.github.io/doc/stable/changelog.html#january-20-2024)), which [scoped `LIEF::EXE_FORMATS` in `LIEF::Binary::FORMATS`](https://github.com/lief-project/LIEF/commit/df97777811ad84134f79694d73cba6c3700c829c).

After fixing this and rerunning the command, another error occurred:
```
Traceback (most recent call last):
  File "/root/src/static-binary-analyser/static_analyser.py", line 126, in <module>
    main()
  File "/root/src/static-binary-analyser/static_analyser.py", line 100, in main
    code_analyser = CodeAnalyser(utils.app)
  File "/root/src/static-binary-analyser/code_analyser.py", line 116, in __init__
    self.__lib_analyser = library_analyser.LibraryUsageAnalyser(
  File "/root/src/static-binary-analyser/library_analyser.py", line 159, in __init__
    self.__binary_path = binary.name
AttributeError: 'Binary' object has no attribute 'name'
```
This is also due to the breaking changes (introduced in 14.0 as well), which [removed the Binary's name attribute](https://github.com/lief-project/LIEF/commit/8908fe4a4551de756b4f50eaca22328571e98fce).

I've created a PR to fix these errors, but I wonder if it's better to pin the lief library at a specific version number, how do you think?

**Comment by gaulthiergain** [comment]
Thank you for your fix. We will apply your PR.
We will regularly monitor the development of lief to have API compliance with the latest version.
