### ISSUE TITLE
Issue in static analysis module

### ISSUE THREAD

**Issue by JeniRotaru** [unikraft/loupe#16]
Running `./loupe generate -b -db ../loupedb -a "nginx" -w "wrk" -d ./Dockerfile.nginx`(same command as in the example) for a Nginx app with wrk, returns the following error :

> [I] Running dynamic analysis in the container (2 replicas)...
> Traceback (most recent call last):
>   File "/root/src/static-binary-analyser/static_analyser.py", line 126, in <module>
>     main()
>   File "/root/src/static-binary-analyser/static_analyser.py", line 90, in main
>     if not is_valid_binary(binary):
>   File "/root/src/static-binary-analyser/elf_analyser.py", line 64, in is_valid_binary
>     and binary.header.identity_class == lief.ELF.ELF_CLASS.CLASS64
> AttributeError: module 'lief._lief.ELF' has no attribute 'ELF_CLASS'
> Traceback (most recent call last):
>   File "/root/src/static-binary-analyser/static_analyser.py", line 126, in <module>
>     main()
>   File "/root/src/static-binary-analyser/static_analyser.py", line 90, in main
>     if not is_valid_binary(binary):
>   File "/root/src/static-binary-analyser/elf_analyser.py", line 64, in is_valid_binary
>     and binary.header.identity_class == lief.ELF.ELF_CLASS.CLASS64
> AttributeError: module 'lief._lief.ELF' has no attribute 'ELF_CLASS'
> Traceback (most recent call last):
>   File "/root/explore.py", line 738, in <module>
>     print(subprocess.check_output(runcmd).decode('utf-8'))
>   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
> Traceback (most recent call last):
>   File "/root/explore.py", line 738, in <module>
>     print(subprocess.check_output(runcmd).decode('utf-8'))
>   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/root/src/static-binary-analyser/static_analyser.py', '-a', '/root/nginx/objs/nginx', '--csv=true', '--display=false', '--verbose=false']' returned non-zero exit status 1.
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/root/src/static-binary-analyser/static_analyser.py', '-a', '/root/nginx/objs/nginx', '--csv=true', '--display=false', '--verbose=false']' returned non-zero exit status 1.
> [I] Sanitizing replicas outputs...
> [E] Binary static analysis results are invalid (no results!)

A workaround is to pass `--disable-static` option to `explorer.py`

**Comment by gaulthiergain** [comment]
Fixed with issue #17.
