### ISSUE TITLE
Error : Binary static analysis results are invalid

### ISSUE THREAD

**Issue by JeniRotaru** [unikraft/loupe#17]
Running `./loupe generate -b -db ../loupedb -a "nginx" -w "wrk" -d ./Dockerfile.nginx` (same command as in the example) for a Nginx app with wrk, after I passed `--disable-static` option to `explorer.py` in `Dockerfile.nginx`, returns : 

>  1 warning found (use --debug to expand):
>  - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 25)
> [I] Running dynamic analysis in the container (2 replicas)...
> [I] Sanitizing replicas outputs...
> [E] Binary static analysis results are invalid (no results!)

**Comment by gaulthiergain** [comment]
Lief recently updated the version to 0.15 leading to incompatibilities. The commit [7821b7a](https://github.com/unikraft/loupe/commit/7821b7ad6778a4b867710224444f41a27f82c8c5) fixes this issue.

**Comment by JeniRotaru** [comment]
Thank you!
