### ISSUE TITLE
Enable wiki on GitHub

### ISSUE THREAD

**Issue by olivierpierre** [unikraft/loupe#3]
The `README.md` file is a bit long and I believe some of the tutorial can be in wiki pages to make it more readable, @hlef would you mind enabling the wiki in the repo GitHub settings, I don't have the permission to do so.

Once done I'd like to write another tutorial not covered in the current README, concerning self contained programs that do not necessitate external input.

**Comment by hlef** [comment]
@olivierpierre I believe that wikis are now enabled.

**Comment by olivierpierre** [comment]
Thanks!
